Added support for White List of FREE nodes Added support to detect when out of free nodes

diff --git a/haas/head/khAdd b/haas/head/khAdd
--- a/haas/head/khAdd
+++ b/haas/head/khAdd
@@ -8,6 +8,12 @@ node=$1
 echo -n "Acquiring node from HAAS: " > /dev/stderr
 start=$(date +%s)
 ninfo=( $(${HCMD} acquire $node 2>/dev/stderr) )
+
+if [[ $? != 0 ]]; then 
+   echo "ERROR: no free nodes?"
+   exit -1
+fi
+
 end=$(date +%s)
 echo "$((end - start)) seconds" > /dev/stderr
 total_start=$start
